

#define TASKS_NB 9
#define MAX_NB_STATES 5
#define CONTEXT_SWITCH_CAPABILITY STD_OFF


#define GPT_DEINIT_API STD_ON
#define GPT_GET_STATUS_API STD_ON

#define PWM_DEINIT_API STD_ON
#define PWM_GET_STATUS_API STD_ON



#define EEP_DEINIT_API STD_ON
#define EEP_ERASE_API STD_ON
#define EEP_COMPARE_API STD_ON
#define EEP_GET_STATUS_API STD_ON

#define DISPLAY_INNER_DELAY 50   //ms
